name: Deploy API

on:
  push:
    branches:
      - main
    paths:
      - "apps/api/**"
      - ".github/workflows/api.yml"
  pull_request:
    types:
      - "synchronize"
      - "opened"
    paths:
      - "apps/api/**"
      - ".github/workflows/api.yml"

permissions: 
  pull-requests: write
  issues: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy API
    steps:
      - uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Deploy
        id: deploy-api
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: apps/remix-app
          packageManager: bun
          command: pages deploy dist
        
      - name: Add Deployment URL Comment
        if: github.event_name == 'pull_request'
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            API Preview Deployment URL: ${{ steps.deploy-api.outputs.deployment-url }}
          comment_tag: preview-url-api
  