name: Deploy App

on:
  push:
    branches:
      - main
    paths:
      - "apps/remix-app/**"
      - ".github/workflows/app.yml"
  pull_request:
    types:
      - "synchronize"
      - "opened"
    paths:
      - "apps/remix-app/**"
      - ".github/workflows/app.yml"

permissions: 
  pull-requests: write
  issues: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy App
    steps:
      - uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build
        working-directory: apps/remix-app
        run: bun run build

      - name: Deploy
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: apps/remix-app
          packageManager: bun
          command: pages deploy ./build --project-name=full-stack-cloudflare-app
      
      - name: Add Deployment URL Comment
        if: github.event_name == 'pull_request'
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            App Preview Deployment URL: ${{ steps.deploy.outputs.deployment-url }}
          comment_tag: preview-url
