name: Deploy App

on:
  push:
    branches:
      - main
    paths:
      - "apps/remix-app/**"
      - ".github/workflows/app.yml"
  pull_request:
    types:
      - "synchronize"
      - "opened"
    paths:
      - "apps/remix-app/**"
      - ".github/workflows/app.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy App
    steps:
      - uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build
        working-directory: apps/remix-app
        run: bun run build

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: apps/remix-app
          packageManager: bun
          command: pages deploy ./public --project-name=full-stack-cloudflare-app
      
      - name: Add Comment
        uses: actions/github-script@v7
        env:
          DEPLOYMENT_URL: ${{ steps.deploy.outputs.deployment-url }}
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'App Preview Deployment URL: \n\n$DEPLOYMENT_URL'
            })
        # Add comment to current pr with deployment url

        # run: echo $DEPLOYMENT_URL
