name: Deploy Docs

on:
  push:
    branches:
      - main
    paths:
      - "apps/docs/**"
      - ".github/workflows/docs.yml"
  pull_request:
    types:
      - "synchronize"
      - "opened"
    paths:
      - "apps/docs/**"
      - ".github/workflows/docs.yml"

permissions: 
  pull-requests: write
  issues: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy App
    steps:
      - uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build
        working-directory: apps/docs
        run: bun run build

      - name: Deploy
        id: deploy-docs
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: apps/docs
          packageManager: bun
          command: pages deploy .vitepress/dist --project-name=edge-stack-docs
      
      - name: Add Deployment URL Comment
        if: github.event_name == 'pull_request'
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Docs Preview Deployment URL: ${{ steps.deploy-docs.outputs.deployment-url }}
          comment_tag: preview-url-docs
