on: pull_request

jobs:
  lint:
    name: Lint
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Lint API
        run: bun run lint
        working-directory: apps/api

      - name: Lint remix-app
        run: bun run lint
        working-directory: apps/remix-app

  build:
    name: Build
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build API
        run: bun run build
        working-directory: apps/api

      - name: Build remix-app
        run: bun run build
        working-directory: apps/remix-app

  test:
    name: Test API
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Migrate Test DB
        run: bun run migrate:test
        working-directory: apps/api

      - name: Run tests
        run: bun run test
        working-directory: apps/api
